//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MathsDepartmentWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesson
    {
        public int LessonID { get; set; }
        public int TeacherID { get; set; }
        public int TimeslotID { get; set; }
        public int DayID { get; set; }
        public Nullable<bool> Available { get; set; }
        public Nullable<int> SpotsTaken { get; set; }
        public string Subject { get; set; }
    
        public virtual Day Day { get; set; }
        public virtual Teacher Teacher { get; set; }
        public virtual Timeslot Timeslot { get; set; }
    }
}
